// Default workout templates for the application

export const defaultTemplates = [
  {
    id: "default-push",
    name: "Push",
    description:
      "Default push workout focusing on chest, shoulders, and triceps",
    workouts: [
      {
        id: "push-1",
        name: "Bench Press",
        sets: 3,
        reps: "8-12",
        type: "push",
      },
      {
        id: "push-2",
        name: "Overhead Press",
        sets: 5,
        reps: "5",
        amrap: true,
        type: "push",
      },
      {
        id: "push-3",
        name: "Incline Dumbbell Press",
        sets: 3,
        reps: "8-12",
        type: "push",
      },
      {
        id: "push-4",
        name: "Tricep Pushdowns",
        sets: 3,
        reps: "8-12",
        type: "push",
      },
      {
        id: "push-5",
        name: "Lateral Raises",
        sets: 3,
        reps: "15-20",
        type: "push",
      },
    ],
    isDefault: true,
  },
  {
    id: "default-pull",
    name: "Pull",
    description: "Default pull workout focusing on back and biceps",
    workouts: [
      {
        id: "pull-1",
        name: "Deadlifts",
        sets: 5,
        reps: "5",
        amrap: true,
        type: "pull",
      },
      {
        id: "pull-2",
        name: "Pulldowns (or Pullups/Chinups)",
        sets: 3,
        reps: "8-12",
        type: "pull",
      },
      {
        id: "pull-3",
        name: "Chest Supported Rows",
        sets: 3,
        reps: "8-12",
        type: "pull",
      },
      {
        id: "pull-4",
        name: "Face Pulls",
        sets: 5,
        reps: "15-20",
        type: "pull",
      },
      {
        id: "pull-5",
        name: "Dumbbell Curls",
        sets: 4,
        reps: "8-12",
        type: "pull",
      },
    ],
    isDefault: true,
  },
  {
    id: "default-pull-alt",
    name: "Pull Alt",
    description: "Alternate pull workout with different exercises",
    workouts: [
      {
        id: "pull-alt-1",
        name: "Barbell Rows",
        sets: 5,
        reps: "5",
        amrap: true,
        type: "pull",
      },
      {
        id: "pull-alt-2",
        name: "Lat Pulldowns",
        sets: 3,
        reps: "8-12",
        type: "pull",
      },
      {
        id: "pull-alt-3",
        name: "One-Arm Dumbbell Rows",
        sets: 3,
        reps: "8-12",
        type: "pull",
      },
      {
        id: "pull-alt-4",
        name: "Rear Delt Flies",
        sets: 3,
        reps: "15-20",
        type: "pull",
      },
      {
        id: "pull-alt-5",
        name: "Hammer Curls",
        sets: 4,
        reps: "8-12",
        type: "pull",
      },
    ],
    isDefault: true,
  },
  {
    id: "default-legs",
    name: "Legs",
    description: "Default leg workout targeting all lower body muscles",
    workouts: [
      {
        id: "legs-1",
        name: "Squats",
        sets: 3,
        reps: "5",
        amrap: true,
        type: "legs",
      },
      {
        id: "legs-2",
        name: "Romanian Deadlift",
        sets: 3,
        reps: "8-12",
        type: "legs",
      },
      {
        id: "legs-3",
        name: "Leg Press",
        sets: 3,
        reps: "8-12",
        type: "legs",
      },
      {
        id: "legs-4",
        name: "Leg Curls",
        sets: 3,
        reps: "8-12",
        type: "legs",
      },
      {
        id: "legs-5",
        name: "Calf Raises",
        sets: 5,
        reps: "8-12",
        type: "legs",
      },
    ],
    isDefault: true,
  },
];
